name: data100-FA23

channels:
- conda-forge
- pytorch

dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git==2.49.0
  - git-lfs==3.7.0
  - jupyter-archive==3.4.0
  - jupyter-offlinenotebook==0.3.1
  - jupyter-resource-usage==1.1.1
  - jupyter-server-proxy==4.4.0
  - jupyter_server==2.16.0
  - jupyterhub==5.3.0
  - jupyterlab==4.5.0
  - jupyterlab-git==0.51.1
  - jupyterlab_rise==0.43.1
  - jupytext==1.16.6
  - nbgitpuller==1.2.2
  - notebook==7.5.0
  - otter-grader==6.1.3
  - pip==25.1.1
  - python==3.11.*
  - sqlite>=3.40
  - libsqlite>=3.40

  # other packages
  - duckdb==1.3.0
  - duckdb-engine==0.15.0
  - folium==0.19.7
  - h5netcdf==1.6.1
  - ipywidgets==8.1.7
  - jupysql==0.11.1
  - jupyterlab-favorites==3.2.2
  - jupyterlab_server==2.28.0
  - jupyterlab_widgets==3.0.15
  - libclang==18.1.1
  - matplotlib==3.9.2
  - mdit-py-plugins==0.4.2
  - ml_dtypes==0.4.0
  - mlxtend==0.23.4
  - numpy==1.26.4
  - pandas==2.3.0
  - plotly==6.1.2
  - protobuf==5.27.5
  - pytest-notebook==0.10.0
  - requests==2.32.4
  - scikit-image==0.25.0
  - scikit-learn==1.7.0
  - scipy==1.13.1
  - seaborn==0.13.2
  - sqlalchemy==2.0.41
  - statsmodels==0.14.4
  - tensorboard==2.17.1
  - tensorflow-cpu==2.17.0
  - tf-keras==2.17.0
  - ydata-profiling==4.16.1

  # Spring 2024 data 100
  - cpuonly==2.0
  - pytorch==2.5.1
  - transformers==4.52.4
  # Spring 2024 table demos
  - lxml==5.4.0
  # Spring 2024 Econ 148 Packages
  - geopandas==1.1.0
  - geopy==2.4.1
  - lifelines==0.30.0
  - pycountry==24.6.1

  # pip installed pacakges, conda preferred
  - pip:
    # required for basic functionality
    - git-credential-helpers==0.2
    - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
    - nbconvert[webpdf]==7.16.6

    # disable until fixed (probably this:  https://github.com/jupyterlab/jupyter-collaboration/issues/162)
    # DH-418, 2024-01-16, above issue still not fixed.  Also this package is available in condaforge
    # https://anaconda.org/conda-forge/jupyter-collaboration
    # - jupyter_collaboration==1.0.1

    # https://github.com/berkeley-dsep-infra/datahub/issues/7611
    - otter-pensieve==1.6.0
