name: data100-FA23

channels:
- conda-forge
- pytorch

dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git==2.47.1
  - git-lfs==3.7.0
  - jupyter-archive==3.4.0
  - jupyter-offlinenotebook==0.3.1
  - jupyter-resource-usage==1.1.0  
  - jupyter-server-proxy==4.4.0
  - jupyter_server==2.15.0 
  - jupyterhub==5.2.1
  - jupyterlab==4.5.0
  - jupyterlab-git==0.50.2
  - jupyterlab_rise==0.43.1
  - jupytext==1.16.6
  - nbgitpuller==1.2.1
  - notebook==7.5.0
  - otter-grader==6.1.0
  - pip==24.3.1  
  - python==3.11.*

  # other packages
  - duckdb==1.1.3
  - duckdb-engine==0.15.0
  - folium==0.14.0
  - h5netcdf==1.0.2
  - ipywidgets==8.1.5
  - jupysql==0.10.17
  - jupyterlab-favorites==3.2.2
  - jupyterlab_server==2.28.0
  - jupyterlab_widgets==3.0.13
  - libclang==18.1.1
  - matplotlib==3.7.1
  - ml_dtypes==0.4.0
  - protobuf==5.27.5
  - mdit-py-plugins==0.4.0
  - mlxtend==0.23.0
  - numpy==1.24.2
  - pandas==2.0.2
  - plotly==5.13.1
  - pytest-notebook==0.10.0
  - requests==2.32.3
  - scikit-image==0.19.3
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - seaborn==0.13.2
  - sqlalchemy==2.0.16
  - statsmodels==0.14.0
  - tensorboard==2.17.1
  #- tensorflow==2.17.0
  - tensorflow-cpu==2.17.0
  - tf-keras==2.17.0
  - ydata-profiling==4.12.1

  # Spring 2024 data 100
  - cpuonly==2.0
  - pytorch==2.5.1
  - transformers==4.37.1
  # Spring 2024 table demos
  - lxml==5.1.0
  # Spring 2024 Econ 148 Packages
  - geopandas==0.14.2
  - geopy==2.4.1
  - lifelines==0.27.8
  - pycountry==22.3.5

  # pip installed pacakges, conda preferred
  - pip:
    # required for basic functionality
    - git-credential-helpers==0.2
    - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
    - jupytutor==0.1.7
    - nbconvert[webpdf]==7.16.5

    # disable until fixed (probably this:  https://github.com/jupyterlab/jupyter-collaboration/issues/162)
    # DH-418, 2024-01-16, above issue still not fixed.  Also this package is available in condaforge
    # https://anaconda.org/conda-forge/jupyter-collaboration
    # - jupyter_collaboration==1.0.1

    # https://github.com/berkeley-dsep-infra/datahub/issues/7611
    - otter-pensieve==1.6.0
